# Auto-generated by the release workflow in the (private) ElOrlis/carol
# repo on tag v0.1.5. Edit the workflow, not this file directly.
class Carol < Formula
  desc "Project management for Zurdo-driven repositories"
  homepage "https://github.com/ElOrlis/homebrew-zurdo"
  version "0.1.5"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/ElOrlis/carol-dist/releases/download/v0.1.5/carol-v0.1.5-aarch64-apple-darwin.tar.gz"
      sha256 "2e25a3e599a5498eea73d9f1b6d0095449b8c53ccaf8bab4dd7750e0d3a8ced9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ElOrlis/carol-dist/releases/download/v0.1.5/carol-v0.1.5-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "20571955f7e5827295ee991f1ba9b59fe417c53dbfb9135f839bbc10ddeded5a"
    end
    on_intel do
      url "https://github.com/ElOrlis/carol-dist/releases/download/v0.1.5/carol-v0.1.5-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ec213323b1fd969174933310443aaafa77cf8da6c4da87b9bf566fe778b6adab"
    end
  end

  depends_on "gh"

  def install
    bin.install "carol"
    bash_completion.install "completions/carol.bash"
    zsh_completion.install "completions/_carol"
    fish_completion.install "completions/carol.fish"
    man1.install Dir["man/*.1"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/carol --version")
    assert_predicate zsh_completion/"_carol", :exist?
  end
end
