# Auto-generated by the release workflow in the (private) ElOrlis/carol
# repo on tag v0.1.3. Edit the workflow, not this file directly.
class Carol < Formula
  desc "Project management for Zurdo-driven repositories"
  homepage "https://github.com/ElOrlis/homebrew-zurdo"
  version "0.1.3"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/ElOrlis/carol-dist/releases/download/v0.1.3/carol-v0.1.3-aarch64-apple-darwin.tar.gz"
      sha256 "385e39ea9403e63451f7d3d3ba7adea0ddeecbb26c987fe0f5db0d0969bc0e33"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ElOrlis/carol-dist/releases/download/v0.1.3/carol-v0.1.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "fdf24f679bf272d02763bd756eff117d6a73f286e2fe1113f429f43bd9c454f2"
    end
    on_intel do
      url "https://github.com/ElOrlis/carol-dist/releases/download/v0.1.3/carol-v0.1.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b19760ac2a117cd21dfd7445117650e20e1e5279b7989c28ca71ee283facda76"
    end
  end

  depends_on "gh"

  def install
    bin.install "carol"
    bash_completion.install "completions/carol.bash"
    zsh_completion.install "completions/_carol"
    fish_completion.install "completions/carol.fish"
    man1.install Dir["man/*.1"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/carol --version")
    assert_predicate zsh_completion/"_carol", :exist?
  end
end
