# Auto-generated by the release workflow in the (private) ElOrlis/carol
# repo on tag v0.1.6. Edit the workflow, not this file directly.
class Carol < Formula
  desc "Project management for Zurdo-driven repositories"
  homepage "https://github.com/ElOrlis/homebrew-zurdo"
  version "0.1.6"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/ElOrlis/carol-dist/releases/download/v0.1.6/carol-v0.1.6-aarch64-apple-darwin.tar.gz"
      sha256 "c9d986670264cf8d267749a85bb1b8bb7a50a12a0dd766c32cbebecbec6ce0da"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ElOrlis/carol-dist/releases/download/v0.1.6/carol-v0.1.6-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e189cdd20d109468e44037eb2f6bec5da1597bcef3103d4e601d5cb1ca13b3ba"
    end
    on_intel do
      url "https://github.com/ElOrlis/carol-dist/releases/download/v0.1.6/carol-v0.1.6-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "022fa1805299afeb88168941bb7ba3dc6e76d639d452f77e1e27bfe14ffa47e2"
    end
  end

  depends_on "gh"

  def install
    bin.install "carol"
    bash_completion.install "completions/carol.bash"
    zsh_completion.install "completions/_carol"
    fish_completion.install "completions/carol.fish"
    man1.install Dir["man/*.1"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/carol --version")
    assert_predicate zsh_completion/"_carol", :exist?
  end
end
