# Auto-generated by the release workflow in the (private) ElOrlis/zurdo
# repo on tag v1.25.0. Edit the workflow, not this file directly.
class Zurdo < Formula
  desc "Drive LLM agents through a PRD's tasks with independent verification"
  homepage "https://github.com/ElOrlis/homebrew-zurdo"
  version "1.25.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/ElOrlis/zurdo-dist/releases/download/v1.25.0/zurdo-v1.25.0-aarch64-apple-darwin.tar.gz"
      sha256 "a52a486d3737ffca47c0eabd4698a6227060b61afd5a22da5a2206ddf354fd30"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ElOrlis/zurdo-dist/releases/download/v1.25.0/zurdo-v1.25.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f5420dc10d3db2507e9f34ef732b2b8a6864eb03d69f947a24b12bbcc8b00bb7"
    end
    on_intel do
      url "https://github.com/ElOrlis/zurdo-dist/releases/download/v1.25.0/zurdo-v1.25.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5b7caf5789c787a56f48ea68270e451cf01e718a7e2b322e4caab7f143b27393"
    end
  end

  def install
    bin.install "zurdo"
    bash_completion.install "completions/zurdo.bash"
    zsh_completion.install "completions/_zurdo"
    fish_completion.install "completions/zurdo.fish"
    man1.install Dir["man/*.1"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zurdo --version")
    assert_predicate zsh_completion/"_zurdo", :exist?
  end
end
