# Auto-generated by the release workflow in the (private) ElOrlis/zurdo
# repo on tag v1.26.0. Edit the workflow, not this file directly.
class Zurdo < Formula
  desc "Drive LLM agents through a PRD's tasks with independent verification"
  homepage "https://github.com/ElOrlis/homebrew-zurdo"
  version "1.26.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/ElOrlis/zurdo-dist/releases/download/v1.26.0/zurdo-v1.26.0-aarch64-apple-darwin.tar.gz"
      sha256 "e5568893881c5926b880094e80c9dbcff06ff1f7b925126608abe46d74533329"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ElOrlis/zurdo-dist/releases/download/v1.26.0/zurdo-v1.26.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3c56725610feea5dc85709b9903c2d5a56dda842e1991e689b76fffcc36e221a"
    end
    on_intel do
      url "https://github.com/ElOrlis/zurdo-dist/releases/download/v1.26.0/zurdo-v1.26.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "668f72644d3af82f0f882119067833001b5c31499bbb5a1e9a5359f9a4ecda07"
    end
  end

  def install
    bin.install "zurdo"
    bash_completion.install "completions/zurdo.bash"
    zsh_completion.install "completions/_zurdo"
    fish_completion.install "completions/zurdo.fish"
    man1.install Dir["man/*.1"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zurdo --version")
    assert_predicate zsh_completion/"_zurdo", :exist?
  end
end
