# Auto-generated by the release workflow in the (private) ElOrlis/zurdo
# repo on tag v1.10.0. Edit the workflow, not this file directly.
class Zurdo < Formula
  desc "Drive LLM agents through a PRD's tasks with independent verification"
  homepage "https://github.com/ElOrlis/homebrew-zurdo"
  version "1.10.0"
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/ElOrlis/zurdo-dist/releases/download/v1.10.0/zurdo-v1.10.0-aarch64-apple-darwin.tar.gz"
      sha256 "7962915b1cc7ce5ad8b7bf268ffa2eb32d5fd0cec79d0d5c518ef38316543ca4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ElOrlis/zurdo-dist/releases/download/v1.10.0/zurdo-v1.10.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "bdd3016fc68fc7fefd4745d727b8630ffe0adb7147bda5214f0c3cb9cb84cb86"
    end
    on_intel do
      url "https://github.com/ElOrlis/zurdo-dist/releases/download/v1.10.0/zurdo-v1.10.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e220435551549b434c62c3dd81e077462b30dc77dc07f0a72fef14435d9c95e2"
    end
  end

  def install
    bin.install "zurdo"
    bash_completion.install "completions/zurdo.bash"
    zsh_completion.install "completions/_zurdo"
    fish_completion.install "completions/zurdo.fish"
    man1.install Dir["man/*.1"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zurdo --version")
    assert_predicate zsh_completion/"_zurdo", :exist?
  end
end
